import axios from "axios";
import { sendQueryToLawyers } from "./ConnectToSignalR";

const AUTO_MESSAGE_DELAY = 30000; // 30 seconds
const AUTO_MESSAGE_TEXT = "Thank you for your inquiry. I'm reviewing your message and will provide a comprehensive response shortly.";

class AutoMessageService {
  constructor() {
    this.pendingMessages = new Map(); // messageId -> timeoutId
    this.autoMessageIds = new Set(); // Track auto-generated message IDs
  }

  // Schedule auto-message for a user message
  scheduleAutoMessage(userMessageId, userName, queryCategory) {
    const timeoutId = setTimeout(async () => {
      try {
        const autoMessageDto = {
          id: `auto-${Date.now()}`,
          Username: "Legal Assistant",
          Message: AUTO_MESSAGE_TEXT,
          QueryCategory: queryCategory,
          ReceiverUsername: userName,
          IsAutoGenerated: true,
          OriginalMessageId: userMessageId
        };

        // Track this as an auto-message
        this.autoMessageIds.add(autoMessageDto.id);

        // Send via REST API first
        await axios.post(`${import.meta.env.VITE_SEND_TEXT_MESSAGE}`, autoMessageDto, {
          headers: {
            Accept: "*/*",
            "Content-Type": "application/json",
          },
        });

        // Send via SignalR for real-time updates
        await sendQueryToLawyers("SendAutoMessage", autoMessageDto);
        
        console.log("📤 Auto-message sent via API and SignalR:", autoMessageDto);
      } catch (error) {
        console.error("❌ Failed to send auto-message:", error);
      } finally {
        this.pendingMessages.delete(userMessageId);
      }
    }, AUTO_MESSAGE_DELAY);

    this.pendingMessages.set(userMessageId, timeoutId);
  }

  // Cancel auto-message if lawyer responds in time
  cancelAutoMessage(userMessageId) {
    const timeoutId = this.pendingMessages.get(userMessageId);
    if (timeoutId) {
      clearTimeout(timeoutId);
      this.pendingMessages.delete(userMessageId);
      console.log("⏹️ Auto-message cancelled for:", userMessageId);
      return true;
    }
    return false;
  }

  // Check if a message is auto-generated
  isAutoMessage(messageId) {
    return this.autoMessageIds.has(messageId);
  }

  // Override auto-message with real lawyer response
  overrideAutoMessage(autoMessageId, realMessageDto) {
    if (this.autoMessageIds.has(autoMessageId)) {
      this.autoMessageIds.delete(autoMessageId);
      console.log("🔄 Auto-message overridden:", autoMessageId, "->", realMessageDto.id);
      return true;
    }
    return false;
  }

  // Clean up old auto-message IDs (call periodically)
  cleanup() {
    // Keep only recent auto-message IDs (last hour)
    const oneHourAgo = Date.now() - 3600000;
    for (const id of this.autoMessageIds) {
      if (id.startsWith('auto-')) {
        const timestamp = parseInt(id.split('-')[1]);
        if (timestamp < oneHourAgo) {
          this.autoMessageIds.delete(id);
        }
      }
    }
  }
}

export const autoMessageService = new AutoMessageService();